### ISSUE TITLE
CommandTOpen opening a file in new horizontal split instead of in current split

### ISSUE THREAD

**Issue by arifb** [wincent/command-t#318] opened 2017-11-16 19:10 UTC
Hi - there are multiple related issues but none I see that are exact dupes of this. I often vsplit a buffer, nav to that new split and use command t to open a new file in that split.

When I do that, command t opens the new file in a horizontal split (for a total of now 3 splits). I'd like it to just open the new file in the current split. Is there a way to do so? This used to work.

Attached animated gif showing the behaviour.

Thank you.

![split-jank](https://user-images.githubusercontent.com/40671/32910648-aa17e784-cabe-11e7-8c01-783d83801202.gif)

**Comment by wincent** [comment] 2017-11-17 03:27
Want to try patching in #315 to your local copy and see if that fixes it? I can't repro this, but the number of people posting issues like this makes it clear that *something* is going on. I am looking at #315 now to see if it introduces any regressions.

**Comment by wincent** [comment] 2017-11-17 04:01
Going to close this optimistically as #315 is landed to the `master` branch and seems to behave well. Please comment if you're still seeing issues and we can re-open.

**Closed by wincent** 2017-11-17 04:01 UTC
