### ISSUE TITLE
Ignoring ffi-1.9.18 because its extensions are not built.  Try: gem pristine ffi --version 1.9.18

### ISSUE THREAD

**Issue by lencioni** [wincent/command-t#327] opened 2018-02-01 19:42 UTC
When I trigger Command-T for the first time in a session, I see this message

> Ignoring ffi-1.9.18 because its extensions are not built.  Try: gem pristine ffi --version 1.9.18

I've found some other folks who have had luck by doing things like

```
gem update bundler
gem install curb
```

but for me the problem persists. Any suggestions?

- http://lfender6445.github.io/vim-command-t-ignoring-gem-name-because-its-extensions-are-not-buil-try-gem-pristine/
- https://stackoverflow.com/questions/25468766/vim-command-t-ignoring-gem-name-because-its-extensions-are-not-built-try-gem

**Comment by wincent** [comment] 2018-02-03 00:00
Command-T doesn't have any Gem dependencies, and isn't invoking Bundler in any way, so I am not sure where that is coming from. Does a similar thing happen if you just do `:ruby puts 'hi'`? Or maybe do anything that would force Ruby to evaluate the loadpath, like `:ruby require 'ostruct'`?

**Comment by lencioni** [comment] 2018-02-05 16:41
No, neither of those things cause this to happen.

**Comment by jgplane** [comment] 2018-04-09 21:46
Are you using RVM? I had the same issue and noticed that if I run `$ rvm use system` before entering vim, then warning messages go away. It's not a permanent fix, but it might help you find the root cause.

**Comment by lightcap** [comment] 2018-04-15 00:36
I just filed what may be a duplicate of this issue: #330 

If I `rvm` into the version that command-t and vim were compiled against I don't get the issue at all. But any other version I use via `rvm` shows the same behavior. And it's different gems for each of the versions, too.

By way of example after issuing `rvm use 2.4.1`, then going to vim and triggering command-t,  I'm getting:

```Ignoring bcrypt-3.1.11 because its extensions are not built. Try: gem pristine bcrypt --version 3.1.11
Ignoring bindex-0.5.0 because its extensions are not built. Try: gem pristine bindex --version 0.5.0
Ignoring byebug-9.1.0 because its extensions are not built. Try: gem pristine byebug --version 9.1.0
Ignoring executable-hooks-1.3.2 because its extensions are not built. Try: gem pristine executable-hooks --version 1.3.2
Ignoring ffi-1.9.18 because its extensions are not built. Try: gem pristine ffi --version 1.9.18
Ignoring gem-wrappers-1.3.1 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.3.1
Ignoring nio4r-2.1.0 because its extensions are not built. Try: gem pristine nio4r --version 2.1.0
Ignoring nokogiri-1.8.0 because its extensions are not built. Try: gem pristine nokogiri --version 1.8.0
Ignoring pg-0.21.0 because its extensions are not built. Try: gem pristine pg --version 0.21.0
Ignoring puma-3.10.0 because its extensions are not built. Try: gem pristine puma --version 3.10.0
Ignoring sqlite3-1.3.13 because its extensions are not built. Try: gem pristine sqlite3 --version 1.3.13
Ignoring unf_ext-0.0.7.4 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.7.4
Ignoring websocket-driver-0.6.5 because its extensions are not built. Try: gem pristine websocket-driver --version 0.6.5```

Whereas if I do `rvm use 2.5.0` and then open vim with `mvim .` and hit `<leader>-t` I get no errors.

**Comment by lightcap** [comment] 2018-04-15 00:38
> Are you using RVM? I had the same issue and noticed that if I run $ rvm use system before entering vim, then warning messages go away. It's not a permanent fix, but it might help you find the root cause.

I can also verify that using `rvm use system` results in no gem errors as above. So it seems that it's both the version compiled against *and* system that are fine. Any other version using rvm has at least one error.

**Comment by Siemingfong** [comment] 2019-01-31 09:42
I have the same problem and solved.
Try this:
`sudo gem pristine ffi`

**Comment by Pratiquea** [comment] 2019-12-25 23:48
I had the same issue.
The following command worked for me:
```
rvm use system
```

**Comment by vitata78** [comment] 2020-08-13 17:09
> I have the same problem and solved.
> Try this:
> `sudo gem pristine ffi`

I did this and got more problems now((

```
package configuration for libffi is not found
"xcrun clang -o conftest -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin20 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/backward -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0 -I. -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -g -Os -pipe -DHAVE_GCC_ATOMIC_BUILTINS conftest.c  -L. -L/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib -L. -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.Internal.sdk/usr/local/lib   -arch arm64e -arch x86_64   -lruby.2.6   "
In file included from conftest.c:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby.h:33:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/ruby.h:24:10: fatal error: 'ruby/config.h' file not found
#include "ruby/config.h"
         ^~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/ruby.h:24:10: note: did not find header 'config.h' in framework 'ruby' (loaded from '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks')
1 error generated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */


```

**Comment by designervoid** [comment] 2020-11-26 12:19
@vitata78 try this one https://github.com/ffi/ffi/issues/844#issuecomment-733957054

**Comment by KushalBhanot** [comment] 2021-01-31 06:16
> I have the same problem and solved.
> Try this:
> `sudo gem pristine ffi`

Thank you so much for the solution! 🪄
It worked just fine. I was stuck with this warning since yesterday.

**Comment by 127** [comment] 2021-02-24 10:06
Had the ame issue with rbenv after Big Sur 11.2.1 update. Fixed with:
```rbenv use system && sudo gem pristine ffi```

**Comment by ShreeSoftech-Bhuj** [comment] 2021-10-05 10:11
same problem with Xcode 13 - macOS 12.0 Beta
unable to install cocoapods > 1.8.4

**Comment by Hayk-Zohrabyan** [comment] 2022-01-28 12:59
`sudo gem update`

**Comment by AlexandreNascimento-SternTI** [comment] 2022-03-29 23:27
### Run in de project folder

```sudo gem install cocoapods``` to update cocoapods

```sudo gem pristine ffi``` to install/update de package

```pod repo update``` to update all repositories end dependencies

```pod install```  to install  all repositories end dependencies

run your app and be happy

**Comment by wincent** [comment] 2022-08-26 21:13
Given the big rewrite for v6.0.x, I'm closing all older issues as there is unlikely to be anything significant happening on [the `5-x-devel` branch](https://github.com/wincent/command-t/tree/5-x-devel) from here on[^patches]. Feedback issue for 6.0.x is here:

- https://github.com/wincent/command-t/issues/393

[^patches]: Patches and PRs would be welcome, but my personal efforts are going to be directed towards `main`.

**Closed by wincent** 2022-08-26 21:13 UTC
