### ISSUE TITLE
No way to ignore directories with watchman scanner?

### ISSUE THREAD

**Issue by spicyj** [wincent/command-t#215] opened 2016-05-11 23:55 UTC
I use the watchman scanner. When I'm developing in the React repo, we build all our source files to `build/modules/` in a flat dir at the top, but the source files often have longer filenames which makes them appear later. Here's me looking for "ReactNativeComponent.js" where I've typed "ReactNativeComp" – you can see it's low on the list:

![image](https://cloud.githubusercontent.com/assets/6820/15200058/65eaba12-1798-11e6-8ccc-dc5bea256262.png)

I would like to ignore `build/modules/` completely but command-t seemingly doesn't support that based on your docs for wildignore (and a quick skim of the source). It makes sense to me that filtering 30,000 files (or 500,000, as I have it set) could be slow but maybe the filtering could be done efficiently closer to display time since I only end up seeing 30 files at a time?

Thanks. :)

(Side note: is there anything I can do to sort the files within src/ better here?)

**Comment by wincent** [comment] 2016-05-12 00:57
Thanks for bringing this up. I've also felt this a bit with projects where I have stuff under `dist` and `src`, or under `platform-a` and `platform-b` etc.

It's by design that the Watchman scanner doesn't do any filtering, because it would be prohibitively slow if we use the existing mechanism, which effectively calls Vim to do `empty(expand(fnameescape(path)))`. VimL is slow. Say it can filter 50 files per ms, that would still be about 10 seconds to filter your 500k files. The thinking is that if you are using Watchman, then you care about speed, so to hell with filtering...

However, there is hope. For example, we could get Watchman itself to do the filtering (or at least, apply a whitelist) if we added configuration to alter the query sent to Watchman to make use of [the `wildmatch` syntax](https://facebook.github.io/watchman/docs/expr/match.html).  Would be easier if it were a blacklist rather than a whitelist, but alas, I can't see anything in Watchman that could be used to do that. I think this would be pretty easy to do, but it would require us to implement a configuration mechanism that was sufficiently flexible such that you could have this do reasonable things across all the projects that you work across.

We could also consider making filtering an opt-in thing such that you could elect to take the speed hit if you wanted filtering to occur even when using the Watchman scanner. (If you did this you would want to leave your Vim instance open and try not to change directories too often. Not very nice, but...)

Another: let the user provide their own arbitrary filtering function. Would have to be Ruby in order to plug in nicely to the other bits of Command-T. Ruby is slow too, but not as slow as VimL.

Probably the hardest thing of all would be to do the filtering at the end. The matching/scoring part of the code assumes already-filtered input, so if you have `g:CommandTMaxHeight` set to, say, 30, it is only going to return the top 30 files. We'd have to hack it to make it return more than you actually asked for, and even then we would never be sure that we'd have enough to return 30 slots after filtering. I'd be inclined to make this a tunable parameter, so you could ask for, say, 100 and then take your chances.

I think we should definitely do something about this; just need to decide on what...

**Comment by wincent** [comment] 2016-05-12 01:04
If you're curious to see how untenably slow the VimL-based filtering is, you could try this:

```
diff --git a/ruby/command-t/scanner/file_scanner/watchman_file_scanner.rb b/ruby/command-t/scanner/file_scanner/watchman_file_scanner.rb
index d1400d5..4d2ca3d 100644
--- a/ruby/command-t/scanner/file_scanner/watchman_file_scanner.rb
+++ b/ruby/command-t/scanner/file_scanner/watchman_file_scanner.rb
@@ -42,7 +42,7 @@ def paths!
             paths = Watchman::Utils.query(query, socket)
 
             # could return error if watch is removed
-            extract_value(paths, 'files')
+            extract_value(paths, 'files').select { |path| !path_excluded?(path, 0) }
           end
         rescue Errno::ENOENT, WatchmanError
           # watchman executable not present, or unable to fulfil request
```

**Comment by wincent** [comment] 2016-05-12 01:22
Compare that with this, which is still pretty fast:

```
diff --git a/ruby/command-t/scanner/file_scanner/watchman_file_scanner.rb b/ruby/command-t/scanner/file_scanner/watchman_file_scanner.rb
index d1400d5..2fd0ff3 100644
--- a/ruby/command-t/scanner/file_scanner/watchman_file_scanner.rb
+++ b/ruby/command-t/scanner/file_scanner/watchman_file_scanner.rb
@@ -42,7 +42,7 @@ def paths!
             paths = Watchman::Utils.query(query, socket)
 
             # could return error if watch is removed
-            extract_value(paths, 'files')
+            extract_value(paths, 'files').select { |path| path !~ %r{\bbuild/modules/} }
           end
         rescue Errno::ENOENT, WatchmanError
           # watchman executable not present, or unable to fulfil request
```

Would just need to thread the configuration through.

**Comment by wincent** [comment] 2016-05-12 01:48
@spicyj: check out https://github.com/wincent/command-t/commit/35a9e5899e1da2ed7104243677d472d9fef12553 and let me know works for your use case.

**Comment by spicyj** [comment] 2016-05-12 02:35
Works for me. Does it make sense to try to convert the wildignore pattern to a Ruby regex so there aren't two pieces of configuration? I do like Ruby regexes better than Vim's anyway though and would need to look up docs whenever I wanted to change wildignore though so I am also quite fine with this.

"Filter" is a little ambiguous as it could indicate patterns to include or patterns to exclude.

`/build/modules/` didn't work as a pattern for me; `^build/modules/` did. I assume that's intended – maybe update the docs to use `^` or `(?:^|/)`?

Thanks.

**Comment by wincent** [comment] 2016-05-15 22:14
@spicyj: Ok, so I got rid of `g:CommandTFilterRegex` and replaced it with simple inference based on the value of the `g:CommandTWildIgnore`. Current result is [here](https://github.com/wincent/command-t/commit/a41e53b8bd4ee2). Still on the `next` branch but closer to the kind of thing that I would feel comfortable with on the `master` branch, which is where I'll merge it after baking it on `next` for a while.

**Comment by wincent** [comment] 2016-05-17 01:43
Gonna close this for now but feel free to comment if you have any further thoughts.

**Closed by wincent** 2016-05-17 01:43 UTC
