### ISSUE TITLE
Switching buffer with command-t loses cursor position in the buffer

### ISSUE THREAD

**Issue by valentinrusu-movidius** [wincent/command-t#177] opened 2015-10-11 18:13 UTC
If I switch buffers with :bN or other native vim command, the buffer is activated and the cursor is shown when I left it.

If I use the command-t buffers list, then the buffer is activated and the cursor is always positioned on the first line (as if someone would typed gg).

How to prevent this? I searched the doc, then googled it but it's not easy to find this piece of information.

Thanks for this very helpful plugin and for your help.

**Comment by wincent** [comment] 2015-10-11 21:12
Closing as a dupe of https://github.com/wincent/command-t/issues/176

**Closed by wincent** 2015-10-11 21:12 UTC
