### ISSUE TITLE
can't use polish letters

### ISSUE THREAD

**Issue by jligeza** [wincent/command-t#182] opened 2015-11-30 12:10 UTC
Command-T doesn't see files containing polish letters, like żźćńąśłęó. I am also unable to type them in search line. I tried to add `let g:CommandTEncoding = "UTF-8"`, but it changes nothing. 
How can I make this work?

**Comment by wincent** [comment] 2015-11-30 19:38
The inability to type non-ASCII characters at the search prompt is a long-standing, known limitation (see [the original ticket #1535](https://wincent.com/issues/1535) on the old bug tracker). I'd be willing to accept patches to address this, but I don't personally know how it would be done and I am not sure if it's feasible or even possible.

For completeness, I made another comment on the subject [here](https://github.com/wincent/command-t/issues/72#issuecomment-39160416):

> On the whole though, Command-T is not going to be very good with non-ASCII filenames, even if you can fix this issue. It has to set up mappings for key presses, and it does so for the ASCII ones; I don't know how it would do so for non-ASCII key codes. This is a pretty big limitation, but it tends not to be too much of a problem because so much of the tech world (Command-T's target market) sticks to ASCII for filenames.

That issue (#72) probably covers the "not seeing" the files thing, so I'm going to mark this one as a duplicate of that one and we can continue the discussion there if you'd like.

**Closed by wincent** 2015-11-30 19:38 UTC

**Comment by jligeza** [comment] 2015-11-30 20:07
I agree, not being able to type non ascii chars is not world breaking, especially when majority of coders use ascii, although being able to at least see files containing them would be useful. Thank you for your answer.
