### ISSUE TITLE
Fail to compile due to incorrect LDFLAGS (Mac OS X 10.13.1 High Sierra)

### ISSUE THREAD

**Issue by stephenmckinney** [wincent/command-t#316] opened 2017-11-14 03:19 UTC
Following the install instructions, I execute:
```shell
cd ruby/command-t/ext/command-t
ruby extconf.rb
make
```

And get the following error:
```
linking shared-object ext.bundle
ld: warning: directory not found for option '-L/BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/libressl/lib'
ld: warning: directory not found for option '-L/BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/lib'
ld: warning: directory not found for option '-L/BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/libressl/lib'
ld: warning: directory not found for option '-L/BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/lib'
```

These directories are set in `ldflags`. Makefile and output are in this gist:
https://gist.github.com/stephenmckinney/0973368cb0385e5d3a1775df4ffb9e31

**Comment by wincent** [comment] 2017-11-17 03:19
No idea why it's trying to pull in those directories (doesn't repro for me on High Sierra, although I am using Homebrew-installed Ruby so my `Makefile` ends up looking like: https://gist.github.com/wincent/cedf0051114d26c409c9c7704abe875f). Don't see any reason why it would have interest in something marked "internal", and especially nothing to do with libressl.

What happens if you edit the `Makefile` to remove the dodgy references?

**Comment by rojobuffalo** [comment] 2017-12-29 23:53
I got the same error. I removed those references and the next `make` looks like it passed.

Makefile line 88 before:
```
ldflags  = -L.             -L -L/BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/lib
 ```

line 88 after:
```
ldflags  = -L.
```

```
> make
linking shared-object ext.bundle
```

**Comment by markwu** [comment] 2018-03-01 16:42
I can confirmed this bug, and delete those LDFLAGS references, command-t build correct. I use RVM ruby.

My system is osx `10.13.3`
Homebrew version is `1.5.5-16-g9225dac`
RVM version is `1.29.3`
RVM ruby is ruby `2.5.0p0`
System Ruby is `2.3.3p222`

```
ldflags  = -L.             -L /BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/libressl/lib -L/BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/lib
```

I build command-t with the following steps:
```
1. rvm use system
2. ruby extconf.rb
3. make
```

**Comment by skarger** [comment] 2018-03-10 19:16
I had a similar problem using system ruby (2.3.3) on macOS High Sierra 10.13.3. I noticed the `ld` warning when running `make` for Vim itself, as well as for command-t.

```
ld: warning: directory not found for option '-L/BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/libressl/lib'
```

I initially configured the Vim install like so
```
```
Ultimately I installed Ruby with Homebrew.

**Comment by wincent** [comment] 2022-08-26 21:13
Given the big rewrite for v6.0.x, I'm closing all older issues as there is unlikely to be anything significant happening on [the `5-x-devel` branch](https://github.com/wincent/command-t/tree/5-x-devel) from here on[^patches]. Feedback issue for 6.0.x is here:

- https://github.com/wincent/command-t/issues/393

[^patches]: Patches and PRs would be welcome, but my personal efforts are going to be directed towards `main`.

**Closed by wincent** 2022-08-26 21:13 UTC
